export const store = {
  id: 1,
  name: 'FirstSun 药店 · 阳光店',
  address: '阳光路 88 号（演示门店）',
  hours: '08:00–22:00',
  phone: '',
};
export const categories = [
  { id: 'all', name: '全部药品', icon: 'list' },
  { id: 'cold', name: '感冒用药', icon: 'fire' },
  { id: 'stomach', name: '肠胃用药', icon: 'heart' },
  { id: 'skin', name: '皮肤用药', icon: 'medal' },
  { id: 'chronic', name: '慢病用药', icon: 'calendar' },
  { id: 'family', name: '家庭常备', icon: 'home' },
];
// 价格、库存均为演示数据；包装图仅作商品识别，不作为用药依据。
export const drugs = [
  {
    id: 1,
    name: '999 感冒灵颗粒',
    genericName: '感冒灵颗粒',
    category: 'cold',
    specification: '10g × 9袋 / 盒',
    price: 1590,
    stock: 28,
    image: '/static/pharmacy/ganmaoling.jpg',
    manufacturer: '华润三九医药股份有限公司',
    approval: '以实物包装为准',
    rx: false,
  },
  {
    id: 2,
    name: '999 板蓝根颗粒',
    genericName: '板蓝根颗粒',
    category: 'cold',
    specification: '10g × 20袋 / 包',
    price: 1280,
    stock: 56,
    image: '/static/pharmacy/banlangen.jpg',
    manufacturer: '华润三九医药股份有限公司',
    approval: '以实物包装为准',
    rx: false,
  },
  {
    id: 3,
    name: '999 小柴胡颗粒',
    genericName: '小柴胡颗粒',
    category: 'cold',
    specification: '10g × 9袋 / 盒',
    price: 1890,
    stock: 3,
    image: '/static/pharmacy/xiaochaihu.jpg',
    manufacturer: '华润三九医药股份有限公司',
    approval: '以实物包装为准',
    rx: false,
  },
  {
    id: 4,
    name: '阿莫西林胶囊',
    genericName: '阿莫西林胶囊',
    category: 'family',
    specification: '0.25g × 24粒 / 盒',
    price: 1680,
    stock: 12,
    image: '',
    manufacturer: '待接入商品档案',
    approval: '待接入商品档案',
    rx: true,
  },
  {
    id: 5,
    name: '苯磺酸氨氯地平片',
    genericName: '苯磺酸氨氯地平片',
    category: 'chronic',
    specification: '5mg × 28片 / 盒',
    price: 2250,
    stock: 18,
    image: '',
    manufacturer: '待接入商品档案',
    approval: '待接入商品档案',
    rx: true,
  },
  {
    id: 6,
    name: '蒙脱石散',
    genericName: '蒙脱石散',
    category: 'stomach',
    specification: '3g × 10袋 / 盒',
    price: 1950,
    stock: 0,
    image: '',
    manufacturer: '待接入商品档案',
    approval: '待接入商品档案',
    rx: false,
  },
  {
    id: 7,
    name: '医用棉签',
    genericName: '医用棉签',
    category: 'family',
    specification: '100支 / 袋',
    price: 500,
    stock: 99,
    image: '',
    manufacturer: '待接入商品档案',
    approval: '待接入器械备案信息',
    rx: false,
    device: true,
  },
  {
    id: 8,
    name: '红霉素软膏',
    genericName: '红霉素软膏',
    category: 'skin',
    specification: '10g / 支',
    price: 680,
    stock: 16,
    image: '',
    manufacturer: '待接入商品档案',
    approval: '待接入商品档案',
    rx: false,
  },
].map((item) => ({ ...item, barcode: `DEMO00000${item.id}`, active: true }));
